success:
  description: The information about the training pool cloning progress.
  value:
    id: 7ea08f99-5e24-47b4-b61f-c177a868d801
    type: TRAINING.CLONE
    status: SUCCESS
    submitted: '2022-04-07T16:06:15.902'
    started: '2022-04-07T16:06:15.902'
    finished: '2022-04-07T16:06:15.902'
    progress: 100
    parameters:
      training_id: '123456'
    details:
      training_id: '123457'